version: 1

formatters:
  line:
    class: logging.Formatter
    format: "%(asctime)s - %(filename)s - %(name)s - %(levelname)s - %(message)s"

  logstash:
    '()': logstash.LogstashFormatterVersion1
    
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: line
    stream: ext://sys.stdout

  logstash:
    class: logstash.TCPLogstashHandler
    host: logstash
    formatter: logstash
    port: 5044
    level: INFO

loggers:
  app:
    level: INFO
    handlers: [console, logstash]
    propagate: False # does not propagate to root (ensuring information is not logged twice)