version: '3.5'

services:
  ddxfrontend:
    image: 'qlaym/ddxfrontend:newest'
    container_name: 'ddxfrontend'
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:80
     # - 80:3000
      - 9229:9229
    environment:
     # - REACT_APP_GATEWAY_API_HOST=http://localhost:8000
      - REACT_APP_GATEWAY_API_HOST=http://ddx-api-gateway
      #- REACT_APP_GATEWAY_API_PORT=8000
    
    networks:
      - ddx-api-network

networks:
  ddx-api-network:
    name: "ddx-api-network"